#ifndef ER_SMART_METER_H
#define ER_SMART_METER_H

typedef enum {
#if 0
  RESOURCES_METER = 0,
  RESOURCES_METER_POWER_HISTORY,
#endif
  RESOURCES_METER_POWER_HISTORY_QUERY = 0,
  RESOURCES_METER_POWER_HISTORY_ROLLUP,
#if 0
  RESOURCES_METER_ENERGY_HISTORY,
  RESOURCES_METER_ENERGY_HISTORY_QUERY,
  RESOURCES_METER_ENERGY_HISTORY_ROLLUP,
#endif
  RESOURCES_SIZE
} resource;

typedef enum {
  ENCODING_XML = 0,
  ENCODING_EXI,
  NR_ENCODINGS
} encoding;

#define ERR_BLOCKOUTOFSCOPE   -2
#define ERR_WRONGCONTENTTYPE  -3
#define ERR_ALLOC             -4

#define MSG_MAX_SIZE  1024

#endif /*ER_SMART_METER_H*/

