#ifndef REST_SMART_METER_H
#define REST_SMART_METER_H

#if !(POWERTRACE)
typedef enum {
  RESOURCES_METER = 0,
#if 0
  RESOURCES_METER_POWER_HISTORY,
  RESOURCES_METER_POWER_HISTORY_QUERY = 0,
  RESOURCES_METER_POWER_HISTORY_ROLLUP,
  RESOURCES_METER_ENERGY_HISTORY,
  RESOURCES_METER_ENERGY_HISTORY_QUERY,
  RESOURCES_METER_ENERGY_HISTORY_ROLLUP,
#endif
  RESOURCES_SIZE
} resource;

#define ERR_BLOCKOUTOFSCOPE   -2
#define ERR_ALLOC             -4

#define MSG_MAX_SIZE  1024
#endif /* !(POWERTRACE) */

#endif /*REST_SMART_METER_H*/

